{% metadata_file .yamato/common.metafile %}
---

build:
  name: Build
  agent:
    image: {{agent_image.automation_tooling_macos_14_arm64_unity}}
    flavor: m1.mac
    type: Unity::VM::osx
    model: M1
  artifacts:
    artifacts:
      paths:
        - dist/idb.tar.zst
      type: single-file
  timeout: 1
  commands:
    - brew install xcodegen
    - .yamato/build-frameworks.sh dist
    - cd dist/Frameworks && tar --zstd --options zstd:compression-level=19 -cf ../idb.tar.zst .

upload-artifacts:
  name: Publish to Stevedore Testing
  agent:
    image: {{agent_image.slough_ops_ubuntu_22_04_base}}
    flavor: b1.small
    type: Unity::VM
  dependencies:
    - .yamato/build.yml#build
  commands: 
    - |-
      set -euo pipefail
      curl -sSo StevedoreUpload "$STEVEDORE_UPLOAD_TOOL_LINUX_X64_URL"
      chmod +x StevedoreUpload
      export STEVEDORE_UPLOAD_KEY="$STEVEDORE_UPLOAD_KEY_IDB"
      ./StevedoreUpload --version-len=12 --repo=testing --version="$GIT_REVISION" dist/idb.tar.zst
